"""Video helpers. Uses a tiny clip generated by ffmpeg; no API calls, no speech model."""
import subprocess

import pytest

from core import video
from core.config import VIDEO_MAX_FRAMES, VIDEO_MIN_FRAMES
from core.tagger import media_blocks


def test_pick_timestamps_bounds_and_spacing():
    for duration, scenes in [(3, []), (19, [3.7, 8.2, 11.1, 15.9]), (60, [i * 0.5 for i in range(100)])]:
        ts = video.pick_timestamps(duration, scenes)
        assert VIDEO_MIN_FRAMES <= len(ts) <= VIDEO_MAX_FRAMES
        assert ts == sorted(ts) and all(0 <= t <= duration for t in ts)


def test_pick_timestamps_uses_scene_changes():
    ts = video.pick_timestamps(19, [3.7, 8.2, 11.1, 15.9])
    for cut in [3.7, 8.2, 11.1, 15.9]:
        assert any(abs(t - (cut + 0.3)) < 0.01 for t in ts)


def test_fmt_time():
    assert video.fmt_time(0.5) == "0:00.5"
    assert video.fmt_time(75.25) == "1:15.2"


def test_media_blocks_image_vs_video():
    assert [b["type"] for b in media_blocks([(None, b"x")], None)] == ["image"]
    blocks = media_blocks([(0.5, b"x"), (2.0, b"y")], {"language": "en", "segments": [
        {"start": 0.0, "end": 1.0, "text": "Hello"}]}, has_audio=True)
    assert [b["type"] for b in blocks] == ["text", "image", "text", "image", "text"]
    assert "Frame at 0:00.5" in blocks[0]["text"] and "Hello" in blocks[-1]["text"]
    silent = media_blocks([(0.5, b"x")], {"language": None, "segments": []}, has_audio=True)
    assert "No speech detected" in silent[-1]["text"]


@pytest.fixture(scope="module")
def clip(tmp_path_factory):
    """4 s clip: 2 s red then 2 s blue (one hard cut), with a sine-tone audio track."""
    path = tmp_path_factory.mktemp("v") / "clip.mp4"
    ff = video._find("ffmpeg")
    r = subprocess.run([ff, "-hide_banner", "-loglevel", "error", "-y",
                        "-f", "lavfi", "-i", "color=red:s=320x240:d=2:r=10",
                        "-f", "lavfi", "-i", "color=blue:s=320x240:d=2:r=10",
                        "-f", "lavfi", "-i", "sine=frequency=440:duration=4",
                        "-filter_complex", "[0:v][1:v]concat=n=2:v=1:a=0[v]",
                        "-map", "[v]", "-map", "2:a", "-pix_fmt", "yuv420p", "-shortest", str(path)],
                       capture_output=True)
    assert r.returncode == 0, r.stderr
    return path


def test_probe_scene_and_extract(clip, tmp_path):
    meta = video.probe(clip)
    assert meta["has_audio"] and meta["width"] == 320 and 3.5 < meta["duration"] < 4.5
    cuts = video.scene_changes(clip)
    assert any(1.8 < c < 2.2 for c in cuts)
    assert video.extract_frame(clip, 1.0)[:8] == b"\x89PNG\r\n\x1a\n"
    wav = tmp_path / "a.wav"
    video.extract_audio(clip, wav)
    assert wav.stat().st_size > 16000 * 2 * 3  # ~4 s of 16 kHz 16-bit mono
